<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <Content Include="Assets\Pads-Continuos\**\*.wav" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Voz-Guia\**\*.mp3" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <None Include="Native\win-x64\bass.dll" Link="bass.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Native\win-x64\bass_fx.dll" Link="bass_fx.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <None Include="Native\osx\libbass.dylib" Link="libbass.dylib" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Native\osx\libbass_fx.dylib" Link="libbass_fx.dylib" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.5" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.5" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="ManagedBass" Version="4.0.2" />
    <PackageReference Include="ManagedBass.Fx" Version="4.0.2" />
    <PackageReference Include="ManagedBass.Mix" Version="4.0.2" />
    <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.3" />
  </ItemGroup>
</Project>
